stages:
  - init
  - validate
  - build
  - deploy

init-terraform:  
  stage: init
  script:
    - terraform init
    - terraform fmt

validate-files:
  stage: validate
  script:
    - terraform validate
    - ansible-playbook -u gabriel_panho -i .ansible-hosts --syntax-check docker-gitlab.yml

build-infrastructure:
  stage: build
  dependencies:
    - init
  script:
    - terraform apply --auto-approve

configure-instances:
  stage: deploy
  dependencies:
    - build
  script:
    - ansible-playbook -u gabriel_panho -i .ansible-hosts docker-gitlab.yml