---
  
- name: Gitlab runner register
  hosts: all:!localhost
  become: true
  vars_prompt:

  - name: gitlab_url
    prompt: Enter gitlab url
    private: no
    
  - name: gitlab_registration_token
    prompt: Enter gitlab registration token
    private: no

  - name: gitlab_runner_name
    prompt: Enter gitlab runner name
    private: no    

  tasks:

  - name: Register runner
    shell: docker exec gitlab-runner gitlab-runner register \
           --non-interactive \
           --name {{gitlab_runner_name}} \
           --url {{ gitlab_url }} \
           --registration-token {{ gitlab_registration_token }} \
           --executor shell