web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: 'gitlab.panho.net'
  environment:
    TZ: 'America/Sao_Paulo'
    GITLAB_OMNIBUS_CONFIG: |

  ports:
    - '80:80'
    - '443:443'
    - '2222:22'
  volumes:
    - '/gitlab/config:/etc/gitlab'
    - '/gitlab/logs:/var/log/gitlab'
    - '/gitlab/data:/var/opt/gitlab'